#!/bin/bash

start_year=2009
quarters=(q1 q2 q3 q4)
current_year=$(date +'%Y')

for (( year=2019; year<=current_year; year++ ))
do
	for quarter in ${quarters[@]}; do
		#curl https://www.sec.gov/files/dera/data/financial-statement-data-sets/$year$quarter.zip --output $year$quarter.zip
		response_code=$(curl -s -o $year$quarter.zip -w "%{http_code}"  https://www.sec.gov/files/dera/data/financial-statement-data-sets/$year$quarter.zip)
		if (( $response_code == 404 ))
		then
			exit 0
		fi
	done
done


